flowchart TD
  %% --- Frontend: źródła ---
  subgraph FE["Frontend: Dodanie Utworu"]
    A["add_song()"]
    B[["POST /api/upload-audio"]]
    A2["add_song_youtube()"]
    B2[["POST /api/download-upload-audio"]]
  end

  %% --- Backend: import i zapis ---
  subgraph BE["Backend: Zapisanie audio"]
    L2A["upload_audio()"]
    AUDIO["Audio"]
    AUDIO-->ADDA
    ADDA["🗄 add_new_song()"]
    L2B["download_audio_yt_dlp()"]
  end

  %% --- Konwersja do MIDI ---
  subgraph CONV[Frontend:Konwersja do MIDI]
    CONT["convert_file()"]
    F[[POST /api/convert-audio]]
  end

  subgraph BE2["Backend: Konwersja do MIDI"]
   G1["convert_audio()"]
   MIDI[MIDI]
  end

  %% --- Eksport notacji z MIDI ---
  subgraph EXP["Eksport notacji z MIDI"]
    MXML[MusicXML]
    LILY[Plik .ly]
    PDF["PDF"]
  end

  %% --- Przepływ ---
  A -->|plik .mp3| B
  A2 -->|YouTube URL| B2

  B --> L2A --> AUDIO
  B2 --> L2B --> AUDIO

  ADDA --> CONT
  CONT --> F  --> G1 
  G1 -- transkun --> MIDI
  G1 -- basic bitch --> MIDI

  MIDI -->|music21| MXML
  MIDI -->|music21 | LILY -->|LilyPond: kompilacja| PDF

  %% --- Kolory / style ---
  classDef fe fill:#fff2d9,stroke:#d6a85b,stroke-width:1px;
  classDef api fill:#d0e0f0,stroke:#99a,stroke-width:1px;
  classDef db fill:#eeeeff,stroke:#7f8ac6,stroke-width:1px;
  classDef be fill:#f6f6f6,stroke:#bbb,stroke-width:1px;
  classDef core fill:#ffeccc,stroke:#d6a85b,stroke-width:1px;
  classDef tmp fill:#f0fff0,stroke:#9bc79b,stroke-width:1px;
  classDef out fill:#e8f4ff,stroke:#7fb3e6,stroke-width:1px;

  class A,A2,CONT fe;
  class G1 fe;
  class B,B2,F api;
  class L2A,ADDA,L2B db;
  class G2,BE,BE2 be;
  class MIDI,AUDIO out;
  class LILY tmp;
  class MXML,PDF out;
